name: C/C++ CI

on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: pip install cpplint
    - name: lint
      run: cpplint --filter=-legal/copyright,-build/c++11,-runtime/references --recursive --exclude=test/cute --exclude=.metadata .
  test:
    runs-on: ubuntu-latest
    container: gcc:latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        apt update
        apt install cmake make python3 python3-pip -y
        pip install gcovr
    - name: test
      run: |
        mkdir build
        cd build
        cmake ..
        make unit_tests
        ./unit_tests
        cd ../ && gcovr -r . -e "test/build/cute*" -e "test/build/ide_listener.h" -e "test/build/xml_listener.h" -e "test/build/SPWL-test.cpp" -e "lib/include/crc16.h" -e "lib/build/crc16.h" -e "test/cute"
