name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: pip install cpplint
    - name: lint
      run: make lint
  test:
    runs-on: ubuntu-latest
    container: gcc:latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        sudo apt update
        sudo apt install make python python-pip -y
        sudo pip install gcovr
    - name: test
      run: |
        make build_test
        make run_test
